"""initial: all tables

Revision ID: 97b14d845575
Revises: 
Create Date: 2026-05-21 14:47:54.968881
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '97b14d845575'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('local', 's3', 'sftp', name='storagetype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('client_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('download_url', sa.String(length=512), nullable=True),
    sa.Column('mirror_url', sa.String(length=512), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_versions_version'), 'client_versions', ['version'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', name='clientstatus'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('client_version', sa.String(length=32), nullable=True),
    sa.Column('config_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_uuid'), 'clients', ['uuid'], unique=True)
    op.create_table('policy_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backup_directories', sa.JSON(), nullable=True),
    sa.Column('backup_usb', sa.Boolean(), nullable=True),
    sa.Column('incremental', sa.Boolean(), nullable=True),
    sa.Column('backup_meta_log', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.Enum('cron', 'interval', 'manual', name='scheduletype'), nullable=True),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.Column('upload_storage_id', sa.Integer(), nullable=True),
    sa.Column('server_address', sa.String(length=256), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('compression_enabled', sa.Boolean(), nullable=True),
    sa.Column('version_update_policy', sa.Enum('force', 'after_task', 'idle', name='versionupdatepolicy'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['upload_storage_id'], ['storages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('source_device', sa.String(length=256), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', name='backupstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_records_client_id'), 'backup_records', ['client_id'], unique=False)
    op.create_table('client_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARN', 'ERROR', name='loglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_logs_client_created', 'client_logs', ['client_id', 'created_at'], unique=False)
    op.create_table('client_policy_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('policy_template_id', sa.Integer(), nullable=True),
    sa.Column('override_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_template_id'], ['policy_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('group_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('policy_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_template_id'], ['policy_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('policy_template_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_template_id'], ['policy_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_policies')
    op.drop_table('group_policies')
    op.drop_table('client_policy_overrides')
    op.drop_index('ix_client_logs_client_created', table_name='client_logs')
    op.drop_table('client_logs')
    op.drop_index(op.f('ix_backup_records_client_id'), table_name='backup_records')
    op.drop_table('backup_records')
    op.drop_table('policy_templates')
    op.drop_index(op.f('ix_clients_uuid'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_client_versions_version'), table_name='client_versions')
    op.drop_table('client_versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('storages')
    op.drop_table('groups')
    # ### end Alembic commands ###
